trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - client/*

variables:
  - name: solutionDirectory
    value: client/
  - name: dotnetArtifactname
    value: client
  - name: publishedProjectAssemblyName
    value: coIT.BewirbDich.Winforms.UI
  
stages:
  - template: ../.azure-pipelines/templates/stages/dotnet-build-stage.yaml
    parameters:
      solutionDirectory: ${{ variables.solutionDirectory }}
      skipTests: true
      projectToPublish: ${{ variables.solutionDirectory }}/${{ variables.publishedProjectAssemblyName }}/${{ variables.publishedProjectAssemblyName }}.csproj
      dotnetArtifactname: ${{ variables.dotnetArtifactname }}