parameters:
  - name: solutionDirectory
    displayName: The path to the dotnet solution (*.sln)
    type: string
  - name: runTests
    displayName: Value indication whether the tests should be executed or not
    type: boolean
    default: false
  - name: projectToPublish
    displayName: The path to the dotnet project that should be published
    type: string
    default: ""
  - name: dotnetArtifactName
    displayName: The name of the dotnet artifact that is published
    type: string

stages:
  - stage: DotnetBuildStage
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: DotnetBuild
        displayName: Building .NET Project
        workspace:
          clean: outputs
        steps:
          - checkout: self
          - template: ../steps/dotnet-build-and-test.yaml
            parameters:
              solutionDirectory: ${{ parameters.solutionDirectory }}
              runTests: ${{ parameters.runTests }}
              publishProjectPath: ${{ parameters.projectToPublish }}
              dotnetArtifactName: ${{ parameters.dotnetArtifactName }}