trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - api/*

variables:
  - name: solutionDirectory
    value: api/
  - name: dotnetArtifactname
    value: api
  - name: publishedProjectAssemblyName
    value: CodeSpire.Api
  
stages:
  - template: ../.azure-pipelines/templates/stages/dotnet-build-stage.yaml
    parameters:
      solutionDirectory: ${{ variables.solutionDirectory }}
      skipTests: true
      projectToPublish: ${{ variables.solutionDirectory }}/${{ variables.publishedProjectAssemblyName }}/${{ variables.publishedProjectAssemblyName }}.csproj
      dotnetArtifactname: ${{ variables.dotnetArtifactname }}